name: Test Godot Project

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: MikeSchulze/gdUnit4-action@v1.0.4
      with:
        godot-version: '4.2.1'
        godot-status: 'stable'
        paths: 'res://test'
        version: 'installed'
        #working-directory: src
